### PR TITLE
CloudFront invalidation support

### LINKED ISSUE #10: Cache invalidation using serverless framework
Could you add CloudFront cache invalidation to this plugin like it's done in `serverless-single-page-app-plugin`: [invalidation function](https://github.com/erezrokah/serverless-monorepo-app/blob/5e52ac580bd76970d5eb598cfcf24228a1912821/frontend/serverless-single-page-app-plugin/index.js#L89)?

### PR DESCRIPTION
**Pull request by hakimio**
Introduced CloudFront invalidation support.

Closes #10

### CODE REVIEW

**Comment by hakimio** [comment]
[Travis Walker PR](https://github.com/DaySmart/fullstack-serverless/tree/cloudfront-invalidation) might be actually much better solution.

**Comment by hakimio** [comment]
I'll try to incorporate some of his ideas.

**Comment by hakimio** [comment]
The PR was rewritten to incorporate some great ideas from Travis Walker PR.
Big THANKS to @traviswalker26 for his contribution.

**Comment by hakimio** [comment]
@andrewphahn the PR is ready for review.

**Comment by traviswalker26** [comment]
Thank you @hakimio. This looks really good.

**Comment by andrewphahn** [comment]
Looks awesome!

**Pull request merged**
